name: Semantic Versioning Parser
description: This application parse semantic version.
version: 1.0.0

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  parameterized_test: ^0.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
